const translations = {
    en: {
        titleTag: "CS2 Float Calculator",
        mainTitle: "CS2 Float Calculator",
        langLabel: "🌐",
        tabFloat: "Calculate Final Float",
        tabAvg: "Calculate Max Avg Float",
        floatStep1: "1. Enter 10 floats for CS2 weapons",
        calcAvgBtn: "Calculate average",
        floatStep2: "2. Enter Max/Min Cap",
        maxCapLabel: "Max Cap:",
        minCapLabel: "Min Cap:",
        calcFloatBtn: "Calculate final float",
        avgStep2: "2. Calculate Max Avg Float",
        skinSearchLabel: "Search skin:",
        skinSearchPlaceholder: "e.g. AK-47 | Redline",
        targetFloatLabel: "Target wear:",
        optFactoryNew: "Factory New (0.00 - 0.0699999…)",
        optMinimalWear: "Minimal Wear (0.07 - 0.1499999…)",
        optFieldTested: "Field-Tested (0.15 - 0.3799999…)",
        optWellWorn: "Well-Worn (0.38 - 0.4499999…)",
        optBattleScarred: "Battle-Scarred (0.45 - 1.00)",
        maxCap2Label: "Max Cap:",
        minCap2Label: "Min Cap:",
        calcMaxAvgBtn: "Calculate Max Avg Float",
        wearShort: ['FN', 'MW', 'FT', 'WW', 'BS'],
        wearFull: ['Factory New','Minimal Wear','Field-Tested','Well-Worn','Battle-Scarred'],
        // New text variables
        avgResultText: "Average float:",
        avgErrorText: "Please enter all 10 floats!",
        capErrorText: "Please enter Max Cap and Min Cap!",
        avgFirstErrorText: "Please calculate the average first!",
        finalResultText: "Final float:",
        loadingSkinsText: "Loading skins...",
        skinErrorText: "Error loading skins",
        floatRangeText: "Float:",
        skinSelectErrorText: "Please select skin and wear!",
        maxAvgResultText: "Max Avg Float for",
        // Filter translations
        filterButtonText: "Filter",
        filterPopupTitle: "Filter Options",
        rarityFilterLabel: "Rarity:",
        collectionFilterLabel: "Collections:",
        applyFiltersText: "Apply Filters",
        resetFiltersText: "Reset Filters",
        closeFilterPopupText: "Close",
        noResultsText: "No results found"
    },
    de: {
        titleTag: "CS2 Float Calculator",
        mainTitle: "CS2 Float Calculator",
        langLabel: "🌐",
        tabFloat: "Finalen Float berechnen",
        tabAvg: "Max. Durchschnitt berechnen",
        floatStep1: "1. Gib 10 Floats für CS2-Waffen ein",
        calcAvgBtn: "Durchschnitt berechnen",
        floatStep2: "2. Max/Min Cap eingeben",
        maxCapLabel: "Max Cap:",
        minCapLabel: "Min Cap:",
        calcFloatBtn: "Finalen Float berechnen",
        avgStep2: "2. Max. Durchschnitts-Float berechnen",
        skinSearchLabel: "Skin suchen:",
        skinSearchPlaceholder: "z.B. AK-47 | Redline",
        targetFloatLabel: "Ziel-Abnutzung:",
        optFactoryNew: "Fabrikneu (0.00 - 0.0699999…)",
        optMinimalWear: "Minimale Gebrauchsspuren (0.07 - 0.1499999…)",
        optFieldTested: "Einsatzerprobt (0.15 - 0.3799999…)",
        optWellWorn: "Abgenutzt (0.38 - 0.4499999…)",
        optBattleScarred: "Kampfspuren (0.45 - 1.00)",
        maxCap2Label: "Max Cap:",
        minCap2Label: "Min Cap:",
        calcMaxAvgBtn: "Max. Durchschnitt berechnen",
        wearShort: ['FN', 'MW', 'FT', 'WW', 'BS'],
        wearFull: ['Fabrikneu','Minimale Gebrauchsspuren','Einsatzerprobt','Abgenutzt','Kampfspuren'],
        // New text variables
        avgResultText: "Durchschnittlicher Float:",
        avgErrorText: "Bitte alle 10 Floats eingeben!",
        capErrorText: "Bitte Max Cap und Min Cap eingeben!",
        avgFirstErrorText: "Bitte zuerst den Durchschnitt berechnen!",
        finalResultText: "Finaler Float:",
        loadingSkinsText: "Lade Skins...",
        skinErrorText: "Fehler beim Laden der Skins",
        floatRangeText: "Float:",
        skinSelectErrorText: "Bitte Skin und Abnutzung auswählen!",
        maxAvgResultText: "Max. Durchschnitt für",
        // Filter translations
        filterButtonText: "Filter",
        filterPopupTitle: "Filter-Optionen",
        rarityFilterLabel: "Seltenheit:",
        collectionFilterLabel: "Kollektionen:",
        applyFiltersText: "Filter anwenden",
        resetFiltersText: "Filter zurücksetzen",
        closeFilterPopupText: "Schließen",
        noResultsText: "Keine Ergebnisse gefunden"
    }
};
